services:
  to-do:
    build: .
    image: to-do
    container_name: to-do
    ports:
      - '3000:3000'
    volumes:
      - to-do:/etc/todo
    restart: unless-stopped

volumes:
  to-do:
    external: true
